import type { employeeRoles } from "@fixr/schemas/roles";
import type { z } from "zod";
import { type Permission, permissions } from "./permissions";

export type EmployeeRole = z.infer<typeof employeeRoles>;

const roleAbilities: Record<EmployeeRole, Permission[]> = {
	guest: [],
	technician: [
		permissions.serviceOrders.read,
		permissions.serviceOrders.update,
		permissions.serviceOrders.changeStatus,
		permissions.customers.read,
	],
	warehouse: [
		permissions.inventory.read,
		permissions.inventory.update,
		permissions.serviceOrders.read,
	],
	financial: [
		permissions.serviceOrders.read,
		permissions.customers.read,
		permissions.invoices.read,
		permissions.invoices.create,
		permissions.invoices.generate,
		permissions.estimates.read,
		permissions.estimates.create,
	],
	manager: [
		permissions.serviceOrders.read,
		permissions.serviceOrders.create,
		permissions.serviceOrders.update,
		permissions.serviceOrders.changeStatus,
		permissions.serviceOrders.assign,
		permissions.customers.read,
		permissions.customers.create,
		permissions.customers.update,
		permissions.inventory.read,
		permissions.estimates.read,
		permissions.estimates.create,
		permissions.estimates.update,
		permissions.estimates.sendToCustomer,
		permissions.invoices.read,
		permissions.invoices.create,
		permissions.invoices.generate,
		permissions.invoices.send,
		permissions.employees.read,
		permissions.companies.read,
	],
	admin: [
		permissions.auth.login,
		permissions.auth.register,
		permissions.companies.read,
		permissions.companies.update,
		permissions.employees.read,
		permissions.employees.create,
		permissions.employees.update,
		permissions.employees.delete,
		permissions.serviceOrders.read,
		permissions.serviceOrders.create,
		permissions.serviceOrders.update,
		permissions.serviceOrders.delete,
		permissions.serviceOrders.changeStatus,
		permissions.serviceOrders.assign,
		permissions.customers.read,
		permissions.customers.create,
		permissions.customers.update,
		permissions.customers.delete,
		permissions.estimates.read,
		permissions.estimates.create,
		permissions.estimates.update,
		permissions.estimates.delete,
		permissions.estimates.sendToCustomer,
		permissions.invoices.read,
		permissions.invoices.create,
		permissions.invoices.generate,
		permissions.invoices.send,
		permissions.inventory.read,
		permissions.inventory.create,
		permissions.inventory.update,
		permissions.inventory.delete,
		permissions.inventory.adjust,
		permissions.suppliers.read,
		permissions.suppliers.create,
		permissions.suppliers.update,
		permissions.suppliers.delete,
		permissions.settings.read,
		permissions.settings.update,
		permissions.settings.security,
	],
};

export { roleAbilities };
