import { permissions } from "@fixr/permissions/permissions";
import type { SidebarSection } from "./types";

export const sidebarSections: readonly SidebarSection[] = [
	{
		titleKey: "dashboard.sidebar.sections.system",
		items: [
			{
				id: "home",
				labelKey: "dashboard.nav.home",
				href: "/home",
				type: "route",
				icon: "Home",
				permission: permissions.serviceOrders.read,
			},
			{
				id: "notifications",
				labelKey: "dashboard.nav.notifications",
				href: "/notifications",
				type: "route",
				icon: "Bell",
				permission: permissions.companies.read,
			},
			{
				id: "logs",
				labelKey: "dashboard.nav.logs",
				href: "/logs",
				type: "route",
				icon: "List",
				permission: permissions.logs.read,
			},
			{
				id: "settings",
				labelKey: "dashboard.nav.settings",
				icon: "Settings",
				items: [
					{
						id: "profile",
						labelKey: "dashboard.nav.profile",
						href: "/account",
						type: "route",
						icon: "User",
						permission: permissions.companies.read,
					},
					{
						id: "security",
						labelKey: "dashboard.nav.security",
						href: "/settings/security",
						type: "route",
						icon: "Shield",
						permission: permissions.settings.security,
					},
					{
						id: "api-keys",
						labelKey: "dashboard.nav.apiKeys",
						href: "/settings/api-keys",
						type: "route",
						icon: "KeyRound",
						permission: permissions.apiKeys.read,
					},
				],
				type: "menu",
			},
		],
	},
	{
		titleKey: "dashboard.sidebar.sections.modules",
		items: [
			{
				id: "service-orders",
				labelKey: "dashboard.nav.serviceOrders",
				href: "/service-orders",
				type: "route",
				icon: "Clipboard",
				permission: permissions.serviceOrders.read,
			},
			{
				id: "estimates",
				labelKey: "dashboard.nav.estimates",
				href: "/estimates",
				type: "route",
				icon: "HandCoins",
				permission: permissions.estimates.read,
			},
			{
				id: "suppliers",
				labelKey: "dashboard.nav.suppliers",
				href: "/suppliers",
				type: "route",
				icon: "Package",
				permission: permissions.suppliers.read,
			},
			{
				id: "parts",
				labelKey: "dashboard.nav.parts",
				href: "/parts",
				type: "route",
				icon: "Puzzle",
				permission: permissions.parts.read,
			},
			{
				id: "inventory",
				labelKey: "dashboard.nav.inventory",
				href: "/inventory",
				type: "route",
				icon: "Warehouse",
				permission: permissions.inventory.read,
			},
			{
				id: "support",
				labelKey: "dashboard.nav.support",
				href: "/support",
				type: "route",
				icon: "MessageCircleQuestion",
			},
			{
				id: "customers",
				labelKey: "dashboard.nav.customers",
				href: "/customers",
				type: "route",
				icon: "Users",
				permission: permissions.customers.read,
			},
			{
				id: "devices",
				labelKey: "dashboard.nav.devices",
				href: "/devices",
				type: "route",
				icon: "MonitorSmartphone",
				permission: permissions.devices.read,
			},
		],
	},
	{
		titleKey: "dashboard.sidebar.sections.company",
		items: [
			{
				id: "employees",
				labelKey: "dashboard.nav.employees",
				href: "/employees",
				type: "route",
				icon: "ContactRound",
				permission: permissions.employees.read,
			},
		],
	},
];
