ALTER TABLE `models` MODIFY COLUMN `announced` text;--> statement-breakpoint
ALTER TABLE `models` MODIFY COLUMN `status` text;--> statement-breakpoint
ALTER TABLE `models` MODIFY COLUMN `dimensions` text;--> statement-breakpoint
ALTER TABLE `models` MODIFY COLUMN `weight` text;--> statement-breakpoint
ALTER TABLE `models` MODIFY COLUMN `build` text;--> statement-breakpoint
ALTER TABLE `models` MODIFY COLUMN `sim` text;--> statement-breakpoint
ALTER TABLE `models` MODIFY COLUMN `display_type` text;--> statement-breakpoint
ALTER TABLE `models` MODIFY COLUMN `display_size` text;--> statement-breakpoint
ALTER TABLE `models` MODIFY COLUMN `display_resolution` text;--> statement-breakpoint
ALTER TABLE `models` MODIFY COLUMN `display_protection` text;--> statement-breakpoint
ALTER TABLE `models` MODIFY COLUMN `os` text;--> statement-breakpoint
ALTER TABLE `models` MODIFY COLUMN `chipset` text;--> statement-breakpoint
ALTER TABLE `models` MODIFY COLUMN `cpu` text;--> statement-breakpoint
ALTER TABLE `models` MODIFY COLUMN `gpu` text;--> statement-breakpoint
ALTER TABLE `models` MODIFY COLUMN `card_slot` text;--> statement-breakpoint
ALTER TABLE `models` MODIFY COLUMN `internal_memory` text;--> statement-breakpoint
ALTER TABLE `models` MODIFY COLUMN `main_camera` text;--> statement-breakpoint
ALTER TABLE `models` MODIFY COLUMN `main_camera_video` text;--> statement-breakpoint
ALTER TABLE `models` MODIFY COLUMN `selfie_camera` text;--> statement-breakpoint
ALTER TABLE `models` MODIFY COLUMN `selfie_video` text;--> statement-breakpoint
ALTER TABLE `models` MODIFY COLUMN `battery` text;--> statement-breakpoint
ALTER TABLE `models` MODIFY COLUMN `battery_charging` text;--> statement-breakpoint
ALTER TABLE `models` MODIFY COLUMN `network_tech` text;--> statement-breakpoint
ALTER TABLE `models` MODIFY COLUMN `sensors` text;--> statement-breakpoint
ALTER TABLE `models` MODIFY COLUMN `colors` text;--> statement-breakpoint
ALTER TABLE `models` MODIFY COLUMN `models_text` text;--> statement-breakpoint
ALTER TABLE `models` MODIFY COLUMN `price` text;--> statement-breakpoint
ALTER TABLE `models` MODIFY COLUMN `display_size_ratio` text;--> statement-breakpoint
ALTER TABLE `models` MODIFY COLUMN `released` text;